# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/admin/Desktop/5b6b/Decode_A_2Mbps/hdl_netlist/decode_a.cache/wt [current_project]
set_property parent.project_path C:/Users/admin/Desktop/5b6b/Decode_A_2Mbps/hdl_netlist/decode_a.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/admin/Desktop/5b6b/Decode_A_2Mbps/hdl_netlist/decode_a.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog C:/Users/admin/Desktop/5b6b/Decode_A_2Mbps/hdl_netlist/decode_a.srcs/sources_1/imports/sysgen/conv_pkg.v
set_property file_type "Verilog Header" [get_files C:/Users/admin/Desktop/5b6b/Decode_A_2Mbps/hdl_netlist/decode_a.srcs/sources_1/imports/sysgen/conv_pkg.v]
read_verilog -library xil_defaultlib {
  C:/Users/admin/Desktop/5b6b/Decode_A_2Mbps/hdl_netlist/decode_a.srcs/sources_1/imports/sysgen/decode_a_entity_declarations.v
  C:/Users/admin/Desktop/5b6b/Decode_A_2Mbps/hdl_netlist/decode_a.srcs/sources_1/imports/sysgen/synth_reg.v
  C:/Users/admin/Desktop/5b6b/Decode_A_2Mbps/hdl_netlist/decode_a.srcs/sources_1/imports/sysgen/synth_reg_w_init.v
  C:/Users/admin/Desktop/5b6b/Decode_A_2Mbps/hdl_netlist/decode_a.srcs/sources_1/imports/sysgen/xlclockdriver_rd.v
  C:/Users/admin/Desktop/5b6b/Decode_A_2Mbps/hdl_netlist/decode_a.srcs/sources_1/imports/sysgen/decode_a.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/admin/Desktop/5b6b/Decode_A_2Mbps/hdl_netlist/decode_a.srcs/constrs_1/imports/sysgen/decode_a_clock.xdc
set_property used_in_implementation false [get_files C:/Users/admin/Desktop/5b6b/Decode_A_2Mbps/hdl_netlist/decode_a.srcs/constrs_1/imports/sysgen/decode_a_clock.xdc]

read_xdc C:/Users/admin/Desktop/5b6b/Decode_A_2Mbps/hdl_netlist/decode_a.srcs/constrs_1/imports/sysgen/decode_a.xdc
set_property used_in_implementation false [get_files C:/Users/admin/Desktop/5b6b/Decode_A_2Mbps/hdl_netlist/decode_a.srcs/constrs_1/imports/sysgen/decode_a.xdc]

read_xdc C:/Users/admin/Desktop/5b6b/Decode_A_2Mbps/hdl_netlist/decode_a.srcs/constrs_1/new/cons.xdc
set_property used_in_implementation false [get_files C:/Users/admin/Desktop/5b6b/Decode_A_2Mbps/hdl_netlist/decode_a.srcs/constrs_1/new/cons.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top decode_a -part xc7a35tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef decode_a.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file decode_a_utilization_synth.rpt -pb decode_a_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
